######################################################################################The Punisher DiscordMain config ###########################################################################################################
Configversion: "1.6"
#DO NOT TOUCH THIS IT WILL MAKE A NEW CONFIG!!
#This config is for the main config options, if you want to edit the automatic punishments go to punishments.yml

#MYSql settings
MySQL:
  #host use 127.0.0.1 or localhost for localhost
  host: localhost
  #name of the database you want the plugin to use (will create it if it doesn't exist)
  database: punisherdb
  #username and password you want to plugin to use to access the MYSql database
  username: punisher
  password: punisher
  #the port must be an integer, default is 3306
  port: 3306
  #Extra arguments to use in the sql url
  extraArguments: ?useSSL=false
  #should extra debug messages be shown for the sql connection tester?
  debugMode: false

#commands and command aliases you want to be blocked when a player is muted
Muted Commands:
  - "message"
  - "msg"
  - "m"
  - "reply"
  - "r"
  - "pm"
  - "privatemessage"
  - "global"
  - "broadcast"
  - "g"
  - "tc"
  - "nc"

#The ban messages will be shown when ever someone gets banned or blocked from logging in due to a ban, the kick message is for when they get /kicked or kicked by the plugin
#placeholders are %reason% for the ban reason, %days% for the days left, %hours% for the hours left, %minutes% for the minutes left, %seconds% for the seconds left.
#placeholders for the kick & warn message are just %reason% for the reason
#use '&' for colorcodes and '\n' ot go to the next line
Warn Title:
  Enabled: true
  #only %reason% works in the titles
  Title Message: "&4You have been Warned!"
  Subtitle Message: "&4Reason: %reason%!"
  Fade In: 10
  Stay: 100
  Fade Out: 10

Warn Sound:
  Enabled: true
  #       SOUNDNAME:VOLUME:PITCH
  Sound: "UI_TOAST_CHALLENGE_COMPLETE:100:0.5"

Warn Message:
  "\n&cYou have been Warned, Reason: %reason%!
  \n&cYou have done something against our server rules!
  \n&cNext time there may be harsher punishments!
  \n&cDo /rules for the rules and server info!\n"

Mute Title:
  Enabled: true
  #only %reason% works in the titles
  Title Message: "&4You have been Muted!"
  Subtitle Message: "&4Reason: %reason%!"
  Fade In: 10
  Stay: 100
  Fade Out: 10

Mute Sound:
  Enabled: true
  #       SOUNDNAME:VOLUME:PITCH
  Sound: "UI_TOAST_CHALLENGE_COMPLETE:100:0.5"

TempMute Message:
  "\n&cYou have been Muted, reason: &f%reason%!
  \n&cThis mute expires in: %days%d %hours%h %minutes%m %seconds%s!
  \n&cYou have done something against our server rules!
  \n&cSome of our punishments result in a mute with no warning!\n"

PermMute Message:
  "\n&cYou have been Muted, reason: &f%reason%!
  \n&cThis mute is permanent and does not expire!
  \n&cYou have done something against our server rules!
  \n&cSome of our punishments result in a mute with no warning!\n"

TempMute Deny Message:
  "\n&cYou cannot speak! You are Muted! Reason: &f%reason%!
  \n&cThis mute expires in: %days%d %hours%h %minutes%m %seconds%s!
  \n&cYou have done something against our server rules!
  \n&cSome of our punishments result in a mute with no warning!\n"

PermMute Deny Message:
  "\n&cYou cannot speak! You are Muted! Reason: &f%reason%!
  \n&cThis mute is permanent and does not expire!
  \n&cYou have done something against our server rules!
  \n&cSome of our punishments result in a mute with no warning!\n"

#send the player's message to staff chat when a player is denied from speaking because of a mute
SendPlayersMessageToStaffChatOnMuteDeny: false
#tell staff that the player tried to speak but don't send their message to staff chat the above option takes priority over this one
StaffChatOnMuteDeny: true


Kick Message:
  "&cYou have been Kicked from the server!
  \nYou were Kicked for the reason: &f%reason%!
  \nYou have done something against our server rules!
  \nSome of our punishments result in a kick with no warning!"

TempBan Message:
  "&cYou have been Banned from the server!
  \nYou were Banned for the reason: &f%reason%!
  \nThis ban expires in: %days%d %hours%h %minutes%m %seconds%s!
  \nYou have done something against our server rules!
  \nSome of our punishments result in a ban with no warning!"

PermBan Message:
  "&cYou have been Banned from the server!
  \nYou were Banned for the reason: &f%reason%!
  \nThis ban does not expire!
  \nYou have done something against our server rules!
  \nSome of our punishments result in a ban with no warning!"

#How much reputation should be taken off the player for each offence number
#KICK and WARN only have 1 offence
ReputationScale:
  BAN:
    '1': 1
    '2': 2
    '3': 3
    '4': 4
    '5': 4
  MUTE:
    '1': 0.5
    '2': 1
    '3': 1.5
    '4': 2
    '5': 2
  KICK: 0
  WARN: 0.2

#The time in hours in which a player can do /global
/global Cooldown: 24

helpCommand:
  #should there be a custom /help command instead of essentials /help?
  Enabled: true
  TextToUse: "\n- Need help? do /warp tutorial to go through the tutorial.
     \n- Report players using /report <player> <reason> and staff will be notified.
     \n- Need extra help? join our discord and ask around for help!
     \n- Link: http://your-discord-join-link.com\n"
  ColorToUse: "light_purple"

Voting:
  addRepOnVote: true
  amountOfRepToAdd: 0.1


DiscordIntegration:
  Enabled: true
  BotToken: "<insert bot token here>"
  GuildId: "<insert guild Id here>"
  Playing: "your.server.com"
  JoinLink: "http://your-discord-join-link.com"
  RolesIdsToAddToLinkedUser:
    - "role#1id"
    - "role#2id"
    - "role#3id"

  EnableRoleSync: true
  #give permission "punisher.discord.role.<roleid> to groups/user then define put the role id here
  #this will give linked users a role on the discord that corresponds to the permission nodes they have
  RolesToSync:
    - "role#1id"
    - "role#2id"
    - "role#3id"

  EnableJoinLogging: true
  JoinLoggingChannelId: "JoinLoggingChannelId"