######################################################################################The Punisher Main config ###########################################################################################################
Configversion: "1.3.1"
#DO NOT TOUCH THIS IT WILL MAKE A NEW CONFIG!!
#This config is for the main config options, if you want to edit the automatic punishments go to punishments.yml in your bungee folder

#MYSql settings
#host use 127.0.0.1 or localhost for localhost
host: localhost
#name of the database you want the plugin to use (will create it if it doesn't exist)
database: punisherdb
#username and password you want to plugin to use to access the MYSql database
username: punisher
password: punisher
#the port must be an integer, default is 3306
port: 3306
extraArguments: ?useSSL=false

#commands you want to be blocked when a player is muted (BungeeCord only)
Muted Commands:
  - "message"
  - "msg"
  - "m"
  - "reply"
  - "r"
  - "pm"
  - "global"
  - "broadcast"

#The ban messages will be shown when ever someone gets banned or blocked from logging in due to a ban
#placeholders are %reason% for the ban reason, %days% for the days left, %hours% for the days left, %minutes% for the days left, %seconds% for the days left.
TempBan Message:
  "&cYou have been Banned from the server!
  \nYou were Banned for the reason: %reason%!
  \nThis ban expires in: %days%d %hours%h %minutes%m %seconds%s!
  \nYou have done something against our server rules!
  \nSome of our punishments result in a ban with no warning!"
PermBan Message:
  "&cYou have been Banned from the server!
  \nYou were Banned for the reason: %reason%!
  \nThis ban does not expire!
  \nYou have done something against our server rules!
  \nSome of our punishments result in a ban with no warning!"

#The time in hours in which a player can do /global
/global Cooldown: 24

helpCommand:
  #should there be a custom /help command instead of essentials /help?
  Enabled: true
  TextToUse: "\n- Need help? do /warp tutorial to go through the tutorial.\n
     \n- Report players using /report <player> <reason> and staff will be notified.\n
     \n- Need extra help? join our discord and ask around for help!\n
     \n- Link: http://discord.vorplex.net\n"
  ColorToUse: "light_purple"
